// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  PLATFORM_CREDIT_UNIT_USD,
  getPlatformPlans, getPlatformPlanById, upsertPlatformPlan, deletePlatformPlan,
  getPlatformSubscribers, getPlatformSubscriberById, createPlatformSubscriber,
  updatePlatformSubscriber, deletePlatformSubscriber, createSubscriberApiKey,
  getPlatformLedger, adjustPlatformCredits, getSubscriberAccessByApiKey,
  consumeCreditsForUsage, getPlatformOverview,
  PLATFORM_ROLES, hasRole, countPlatformUsers, getPlatformUserById,
  getPlatformUserByUsername, getPlatformUsers, createPlatformUser,
  updatePlatformUser, validatePlatformUserCredentials, getUserPermissions,
  exportDb, importDb,
} from "@/lib/db/index.js";
